
development:
  adapter: postgresql
  database: grocery_development
  host: localhost

test:
  adapter: postgresql
  database: grocery_test
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: grocery_production
  pool: 5
  username: grocery
  password:
